### ISSUE TITLE
[QA] - Corrigir problema de redirecionamento na página "Detalhes do Serviço"

### ISSUE THREAD

**Issue by Matheus-Bernardo** [S204-Inatel-2024-2/AgroControl#106]
Ao clicar no botão "Editar informações" na página "Detalhes do Serviço", o usuário é redirecionado à página de login, como mostrado nas imagens abaixo:

http://localhost:3001/servicedetails/id

-Nota-se que, ao clicar no botão "Editar informações", é redirecionado à página de login 
![Image](https://github.com/user-attachments/assets/c522db9c-6d04-492e-97a2-613811250adf)
![Image](https://github.com/user-attachments/assets/4b60871b-35a1-466e-8b05-8a31dca40807)

**Comment by Izalp** [comment]
Acho que não tem tela pra atualizar cadastro

**Comment by Matheus-Bernardo** [comment]
Foi realizado a implementação de uma nova tela para atualizar o cadastro, e nessa implemetação também foi carregado os dados do serviço a ser carregado.
